/* Generated By:JJTree: Do not edit this line. ASTDivNode.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTDivNode extends SimpleNode
{
    public ASTDivNode(int id)
    {
        super(id);
    }

    public ASTDivNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public Object value(Context context)
    {
        return new Integer(((Integer) jjtGetChild(0).value(context)).intValue() /
            ((Integer) jjtGetChild(1).value(context)).intValue());
    }

}
