/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTExpression extends SimpleNode
{
    public ASTExpression(int id)
    {
        super(id);
    }

    public ASTExpression(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public boolean evaluate(Context context)
    {
        return jjtGetChild(0).evaluate(context);
    }

    public Object value(Context context)
    {
        return jjtGetChild(0).value(context);
    }
}
