/* Generated By:JJTree: Do not edit this line. ASTElseIfStatement.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.runtime.parser.*;

public class ASTElseIfStatement extends SimpleNode
{
    public ASTElseIfStatement(int id)
    {
        super(id);
    }

    public ASTElseIfStatement(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
