/* Generated By:JJTree: Do not edit this line. ASTModNode.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.runtime.parser.*;

public class ASTModNode extends SimpleNode
{
    public ASTModNode(int id)
    {
        super(id);
    }

    public ASTModNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
