/* Generated By:JJTree: Do not edit this line. ASTNotNode.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTNotNode extends SimpleNode
{
    public ASTNotNode(int id)
    {
        super(id);
    }

    public ASTNotNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public boolean evaluate(Context context)
    {
        if (jjtGetChild(0).evaluate(context))
            return false;
        else
            return true;
    }
}
