/* Generated By:JJTree: Do not edit this line. ASTObjectArray.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTObjectArray extends SimpleNode
{
    public ASTObjectArray(int id)
    {
        super(id);
    }

    public ASTObjectArray(Parser p, int id)
    {
        super(p, id);
    }


    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public Object value(Context context)
    {
        int size = jjtGetNumChildren();
        Object[] objectArray = new Object[size];
    
        for (int i = 0; i < size; i++)
        {
            objectArray[i] = jjtGetChild(i).value(context);
        }            
        
        return objectArray;
    }
}
