/* Generated By:JJTree: Do not edit this line. ASTOrNode.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.runtime.parser.*;

public class ASTOrNode extends SimpleNode
{
    public ASTOrNode(int id)
    {
        super(id);
    }

    public ASTOrNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
