/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java */

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTStringLiteral extends SimpleNode
{
    public ASTStringLiteral(int id)
    {
        super(id);
    }

    public ASTStringLiteral(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public Object value(Context context)
    {
        /*
         * This will remove the quotes and then interpolate
         * any variables from the context into the
         * the string.
         */
        return NodeUtils.interpolate(
            getFirstToken().image.substring(
                1, getFirstToken().image.length() - 1), context);
    }
}
