/* Generated By:JJTree: Do not edit this line. ASTSetDirective.java */

package org.apache.velocity.runtime.parser.node;

import java.io.IOException;
import java.io.Writer;

import org.apache.velocity.Context;
import org.apache.velocity.runtime.parser.*;

public class ASTSetDirective extends SimpleNode
{
    public ASTSetDirective(int id)
    {
        super(id);
    }

    public ASTSetDirective(Parser p, int id)
    {
        super(p, id);
    }


    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void render(Context context, Writer writer)
        throws IOException
    {
        Object value = null;
        Node right = jjtGetChild(0).jjtGetChild(0)
                        .jjtGetChild(1).jjtGetChild(0);

        value = right.value(context);
        
        ASTReference left = (ASTReference) jjtGetChild(0)
                        .jjtGetChild(0).jjtGetChild(0);
        
        if (left.jjtGetNumChildren() == 0)
            context.put(left.getFirstToken().image.substring(1), value);
        else
            left.setValue(context, value);
    
    }
}
