/* Generated By:JJTree: Do not edit this line. ASTAndNode.java */

package org.apache.velocity.runtime.parser;

import org.apache.velocity.Context;

public class ASTAndNode extends SimpleNode
{
    public ASTAndNode(int id)
    {
        super(id);
    }

    public ASTAndNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public boolean evaluate(Context context)
    {
        if (jjtGetChild(0).evaluate(context) && 
            jjtGetChild(1).evaluate(context))
            return true;
        else
            return false;
    }
}
