/* Generated By:JJTree: Do not edit this line. ASTGENode.java */

package org.apache.velocity.runtime.parser;

import org.apache.velocity.Context;

public class ASTGENode extends SimpleNode
{
    public ASTGENode(int id)
    {
        super(id);
    }

    public ASTGENode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public boolean evaluate(Context context)
    {
        if (((Integer)jjtGetChild(0).value(context)).intValue() >=
            ((Integer)jjtGetChild(1).value(context)).intValue())
            return true;
        else
            return false;
    }
}
