/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

package org.apache.velocity.runtime.parser;

import java.util.Map;

import org.apache.velocity.Context;
import org.apache.velocity.util.ClassUtils;

public class ASTIdentifier extends SimpleNode
{
    public ASTIdentifier(int id)
    {
        super(id);
    }

    public ASTIdentifier(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public Object invoke(Object result, Context context)
    {
        String identifier = getFirstToken().image;
        String method = "get" + identifier;
        Object newResult;
        
        newResult = ClassUtils.invoke(result, method);
        if (newResult == null)
        {
            method = "get";
            Object[] args = { identifier };
            Class[] ptypes = null;

            // Have to make sure class types are
            // correct for a proper signature match.

            if (result instanceof Map)
            {
                // This can be created once.
                ptypes = new Class[1];
                ptypes[0] = new Object().getClass();
            }

            result = ClassUtils.invoke(result, method, args, ptypes);
        }
        else
            result = newResult;
    
        return result;
    }
}
