/* Generated By:JJTree: Do not edit this line. ASTMulNode.java */

package org.apache.velocity.runtime.parser;

import org.apache.velocity.Context;

public class ASTMulNode extends SimpleNode
{
    public ASTMulNode(int id)
    {
        super(id);
    }

    public ASTMulNode(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public Object value(Context context)
    {
        return new Integer(((Integer) jjtGetChild(0).value(context)).intValue() *
            ((Integer) jjtGetChild(1).value(context)).intValue());
    }

}
