/* Generated By:JJTree: Do not edit this line. ASTText.java */

package org.apache.velocity.runtime.parser;

import java.io.Writer;
import java.io.IOException;

import org.apache.velocity.Context;

public class ASTText extends SimpleNode
{
    public ASTText(int id)
    {
        super(id);
    }

    public ASTText(Parser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void render(Context context, Writer writer)
        throws IOException
    {
        writer.write(NodeUtils.specialText(getFirstToken()) +
            getFirstToken().image);
    }    
}
