/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.apache.velocity.runtime.parser;

public interface ParserConstants {

  int EOF = 0;
  int INDEX_LBRACKET = 1;
  int INDEX_RBRACKET = 2;
  int LBRACKET = 3;
  int RBRACKET = 4;
  int COMMA = 5;
  int DOUBLEDOT = 6;
  int COLON = 7;
  int LEFT_CURLEY = 8;
  int RIGHT_CURLEY = 9;
  int LPAREN = 10;
  int RPAREN = 11;
  int REFMOD2_RPAREN = 12;
  int ESCAPE_DIRECTIVE = 13;
  int SET_DIRECTIVE = 14;
  int DOLLAR = 15;
  int DOLLARBANG = 16;
  int HASH = 19;
  int SINGLE_LINE_COMMENT_START = 20;
  int DOUBLE_ESCAPE = 21;
  int ESCAPE = 22;
  int TEXT = 23;
  int SINGLE_LINE_COMMENT = 24;
  int FORMAL_COMMENT = 25;
  int MULTI_LINE_COMMENT = 26;
  int WHITESPACE = 28;
  int STRING_LITERAL = 29;
  int TRUE = 30;
  int FALSE = 31;
  int NEWLINE = 32;
  int MINUS = 33;
  int PLUS = 34;
  int MULTIPLY = 35;
  int DIVIDE = 36;
  int MODULUS = 37;
  int LOGICAL_AND = 38;
  int LOGICAL_OR = 39;
  int LOGICAL_LT = 40;
  int LOGICAL_LE = 41;
  int LOGICAL_GT = 42;
  int LOGICAL_GE = 43;
  int LOGICAL_EQUALS = 44;
  int LOGICAL_NOT_EQUALS = 45;
  int LOGICAL_NOT = 46;
  int EQUALS = 47;
  int END = 48;
  int IF_DIRECTIVE = 49;
  int ELSEIF_DIRECTIVE = 50;
  int ELSE_DIRECTIVE = 51;
  int STOP_DIRECTIVE = 52;
  int DIGIT = 53;
  int INTEGER_LITERAL = 54;
  int FLOATING_POINT_LITERAL = 55;
  int EXPONENT = 56;
  int LETTER = 57;
  int DIRECTIVE_CHAR = 58;
  int WORD = 59;
  int BRACKETED_WORD = 60;
  int ALPHA_CHAR = 61;
  int ALPHANUM_CHAR = 62;
  int IDENTIFIER_CHAR = 63;
  int IDENTIFIER = 64;
  int DOT = 65;
  int LCURLY = 66;
  int RCURLY = 67;
  int REFERENCE_TERMINATOR = 68;
  int DIRECTIVE_TERMINATOR = 69;
  int EMPTY_INDEX = 70;

  int REFERENCE = 0;
  int REFMODIFIER = 1;
  int REFINDEX = 2;
  int DIRECTIVE = 3;
  int REFMOD2 = 4;
  int DEFAULT = 5;
  int REFMOD = 6;
  int PRE_DIRECTIVE = 7;
  int IN_MULTI_LINE_COMMENT = 8;
  int IN_FORMAL_COMMENT = 9;
  int IN_SINGLE_LINE_COMMENT = 10;

  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"]\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"..\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "<RPAREN>",
    "\")\"",
    "<ESCAPE_DIRECTIVE>",
    "<SET_DIRECTIVE>",
    "<DOLLAR>",
    "<DOLLARBANG>",
    "<token of kind 17>",
    "\"#*\"",
    "\"#\"",
    "\"##\"",
    "\"\\\\\\\\\"",
    "\"\\\\\"",
    "<TEXT>",
    "<SINGLE_LINE_COMMENT>",
    "\"*#\"",
    "\"*#\"",
    "<token of kind 27>",
    "<WHITESPACE>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "<NEWLINE>",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<LOGICAL_AND>",
    "<LOGICAL_OR>",
    "<LOGICAL_LT>",
    "<LOGICAL_LE>",
    "<LOGICAL_GT>",
    "<LOGICAL_GE>",
    "<LOGICAL_EQUALS>",
    "<LOGICAL_NOT_EQUALS>",
    "<LOGICAL_NOT>",
    "\"=\"",
    "<END>",
    "<IF_DIRECTIVE>",
    "<ELSEIF_DIRECTIVE>",
    "<ELSE_DIRECTIVE>",
    "<STOP_DIRECTIVE>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIRECTIVE_CHAR>",
    "<WORD>",
    "<BRACKETED_WORD>",
    "<ALPHA_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<DOT>",
    "\"{\"",
    "\"}\"",
    "<REFERENCE_TERMINATOR>",
    "<DIRECTIVE_TERMINATOR>",
    "<EMPTY_INDEX>",
  };

}
