/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

package org.apache.velocity.runtime.parser;

public interface ParserTreeConstants
{
  public int JJTPROCESS = 0;
  public int JJTVOID = 1;
  public int JJTESCAPEDDIRECTIVE = 2;
  public int JJTESCAPE = 3;
  public int JJTCOMMENT = 4;
  public int JJTTEXTBLOCK = 5;
  public int JJTFLOATINGPOINTLITERAL = 6;
  public int JJTINTEGERLITERAL = 7;
  public int JJTSTRINGLITERAL = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTWORD = 10;
  public int JJTDIRECTIVEASSIGN = 11;
  public int JJTDIRECTIVE = 12;
  public int JJTBLOCK = 13;
  public int JJTMAP = 14;
  public int JJTOBJECTARRAY = 15;
  public int JJTINTEGERRANGE = 16;
  public int JJTMETHOD = 17;
  public int JJTINDEX = 18;
  public int JJTREFERENCE = 19;
  public int JJTTRUE = 20;
  public int JJTFALSE = 21;
  public int JJTTEXT = 22;
  public int JJTIFSTATEMENT = 23;
  public int JJTELSESTATEMENT = 24;
  public int JJTELSEIFSTATEMENT = 25;
  public int JJTSETDIRECTIVE = 26;
  public int JJTLOCALDIRECTIVE = 27;
  public int JJTGLOBALDIRECTIVE = 28;
  public int JJTEXPRESSION = 29;
  public int JJTASSIGNMENT = 30;
  public int JJTORNODE = 31;
  public int JJTANDNODE = 32;
  public int JJTEQNODE = 33;
  public int JJTNENODE = 34;
  public int JJTLTNODE = 35;
  public int JJTGTNODE = 36;
  public int JJTLENODE = 37;
  public int JJTGENODE = 38;
  public int JJTADDNODE = 39;
  public int JJTSUBTRACTNODE = 40;
  public int JJTMULNODE = 41;
  public int JJTDIVNODE = 42;
  public int JJTMODNODE = 43;
  public int JJTNOTNODE = 44;


  public String[] jjtNodeName = {
    "process",
    "void",
    "EscapedDirective",
    "Escape",
    "Comment",
    "Textblock",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "DirectiveAssign",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Index",
    "Reference",
    "True",
    "False",
    "Text",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "LocalDirective",
    "GlobalDirective",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
  };
}
