/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

package org.apache.velocity.runtime.parser;

public interface ParserTreeConstants
{
  public int JJTPROCESS = 0;
  public int JJTVOID = 1;
  public int JJTESCAPEDDIRECTIVE = 2;
  public int JJTESCAPE = 3;
  public int JJTCOMMENT = 4;
  public int JJTNUMBERLITERAL = 5;
  public int JJTSTRINGLITERAL = 6;
  public int JJTIDENTIFIER = 7;
  public int JJTWORD = 8;
  public int JJTDIRECTIVE = 9;
  public int JJTBLOCK = 10;
  public int JJTMAP = 11;
  public int JJTOBJECTARRAY = 12;
  public int JJTINTEGERRANGE = 13;
  public int JJTMETHOD = 14;
  public int JJTREFERENCE = 15;
  public int JJTTRUE = 16;
  public int JJTFALSE = 17;
  public int JJTTEXT = 18;
  public int JJTIFSTATEMENT = 19;
  public int JJTELSESTATEMENT = 20;
  public int JJTELSEIFSTATEMENT = 21;
  public int JJTSETDIRECTIVE = 22;
  public int JJTSTOP = 23;
  public int JJTEXPRESSION = 24;
  public int JJTASSIGNMENT = 25;
  public int JJTORNODE = 26;
  public int JJTANDNODE = 27;
  public int JJTEQNODE = 28;
  public int JJTNENODE = 29;
  public int JJTLTNODE = 30;
  public int JJTGTNODE = 31;
  public int JJTLENODE = 32;
  public int JJTGENODE = 33;
  public int JJTADDNODE = 34;
  public int JJTSUBTRACTNODE = 35;
  public int JJTMULNODE = 36;
  public int JJTDIVNODE = 37;
  public int JJTMODNODE = 38;
  public int JJTNOTNODE = 39;


  public String[] jjtNodeName = {
    "process",
    "void",
    "EscapedDirective",
    "Escape",
    "Comment",
    "NumberLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Reference",
    "True",
    "False",
    "Text",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "Stop",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
  };
}
